version: "3.9"

services:

  postgres:
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGUSER: admin
      PGPASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  postgress-initialisation:
    image: postgres:13-alpine
    environment:
      PGHOST: postgres
      PGUSER: admin
      PGPASSWORD: admin
      SECRET: 'my-secret'
    command: psql -c "CREATE DATABASE testdb"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    image: backend:dev
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/src/app
      - ./backend/storage:/storage
    environment:
      DB_HOST: postgres
      DB_NAME: testdb
      DB_USER: admin
      DB_PASSWORD: admin
      PORT: 8080
      SECRET: 'my-secret'
      RESET: ${RESET:-'false'}
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@admin.admin
      FILE_STORAGE: /storage/
      PASSWORD_STRENGH_VALIDATION: 'false'
    command: ./node_modules/nodemon/bin/nodemon.js -L /src/app/server.js

  frontend:
    image: frontend:dev
    build:
      context: frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 8080
    volumes:
      - ./frontend/:/src/app/

  nginx-frontend:
    image: nginx:dev
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-headers.conf:/etc/nginx/general-security-headers.conf
      - ./nginx/site.dev.conf:/etc/nginx/conf.d/default.conf
    command: sh -c "cat /etc/nginx/conf.d/default.conf ; nginx -g 'daemon off;'"


  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Wweb interface

volumes:
  postgres_data:
