---
version: 2
jobs:
    build-images:
      docker:
          - image: docker:dind
      steps:
          - checkout
          # - run:
          #     name: Installation des dépendances système
          #     command: |
          #         apk add --no-cache git
          # - run:
          #     name: Condition pour les branches
          #     command: |
          #           if [ "$CIRCLE_BRANCH" != "master" ]; then
          #               if [ $(git diff --name-only master..${CIRCLE_BRANCH} | grep "sources/metadata.json" | wc -l) = 0 ]; then
          #                 commit_id_head=$(git log -n1 --format=format:"%H")
          #                 commit_id_head1=$(git log -n2 --format=format:"%H" | tail -1)
          #                 if [ $(git diff --name-only ${commit_id_head1} ${commit_id_head} | grep "sources/metadata.json" | wc -l) = 0 ]; then
          #                   circleci-agent step halt
          #                 fi
          #               fi
          #           fi
          - run: date +%F > date
          - run:
              name: Installation des dépendances système
              command: |
                  apk add --no-cache curl py-pip python3-dev libffi-dev openssl-dev gcc libc-dev rust cargo make
                  curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  chmod +x /usr/local/bin/docker-compose
                  ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          - run:
              name: construction des images
              command: |
                  ./scripts/prod/build.sh
          - store_artifacts:
              path: ./deploy
              destination: deploy

workflows:
    version: 2

    dev:
      jobs:
        - build-images
