---
version: 2
jobs:
    build-images:
      docker:
          - image: docker:dind
      steps:
          - checkout
          - run: date +%F > date
          - run:
              name: Installation des dépendances système
              command: |
                  apk add --no-cache docker-compose bash git
          - setup_remote_docker
          - run:
              name: construction des images
              command: |
                  ./scripts/prod/build.sh
          - run:
              name: Compress Artifacts
              command: tar -cvzf deploy.tar.gz ./deploy

          - store_artifacts:
              path: ./deploy.tar.gz

workflows:
    version: 2

    dev:
      jobs:
        - build-images
